### ISSUE TITLE
OmniParser.acceptedPaths(Path rootDir, Path searchDir) ignores searchDir in case rootDir is a git repository

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-polyglot#24]
## What version of OpenRewrite are you using?

org.openrewrite.rewrite.gradle.plugin:6.5.0
org.openrewrite.recipe:rewrite-recipe-bom:2.5.0

## How are you running OpenRewrite?

I apply OpenRewrite to individual Gradle projects, and I do not apply the plugin to the root project.
I execute `./gradlew :benchmarks:rewriteRun`, and I expect OpenRewrite would not attempt parsing files outside of `:benchmarks` projects.

## What is the smallest, simplest way to reproduce the problem?

Pull https://github.com/pgjdbc/pgjdbc/pull/2979, execute `./gradlew :benchmarks:rewriteRun`

## What did you see instead?

As you might see below, openrewrite parses sources which are not related to "benchmarks" project.
I believe the root cause is that `OmniParser` ignores the searchDir, and it effectively causes parsing the same files multiple times: https://github.com/openrewrite/rewrite-polyglot/blob/21833f2a67a8d37e836b516d58d351ad5cf9f002/src/main/java/org/openrewrite/polyglot/OmniParser.java#L117-L151 

```
> Task :benchmarks:rewriteRun
Caching disabled for task ':benchmarks:rewriteRun' because:
  Caching has not been enabled for the task
Task ':benchmarks:rewriteRun' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Validating active recipes
Scanning sources in project :benchmarks
Using active styles [io.github.pgjdbc.style.Style, org.openrewrite.java.Checkstyle]
The configuration :benchmarks:rewriteimplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewriteimplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewriteimplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewriteimplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewritetestImplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewritetestImplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewritetestImplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewritetestImplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewritejmhImplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewritejmhImplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewritejmhImplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewritejmhImplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Scanned 20 Java sources in :benchmarks/jmh
The configuration :benchmarks:jandexClasspath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:jandexClasspath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:jmh is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:jmh is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewrite is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewrite is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewriteimplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewriteimplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewritejmhImplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewritejmhImplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :benchmarks:rewritetestImplementation is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :benchmarks:rewritetestImplementation is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Error during rewrite run
org.openrewrite.json.JsonParsingException: Syntax error in pgjdbc/docs/layouts/index.searchindex.json at line 2:5 no viable alternative at input '{{'.
<------>at org.openrewrite.json.JsonParser$ForwardingErrorListener.syntaxError(JsonParser.java:90)
<------>at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
<------>at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
<------>at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
<------>at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
<------>at org.openrewrite.json.internal.grammar.JSON5Parser.obj(JSON5Parser.java:262)
<------>at org.openrewrite.json.internal.grammar.JSON5Parser.value(JSON5Parser.java:435)
<------>at org.openrewrite.json.internal.grammar.JSON5Parser.arr(JSON5Parser.java:509)
<------>at org.openrewrite.json.internal.grammar.JSON5Parser.value(JSON5Parser.java:442)
<------>at org.openrewrite.json.internal.grammar.JSON5Parser.json5(JSON5Parser.java:155)
<------>at org.openrewrite.json.JsonParser.lambda$parseInputs$0(JsonParser.java:52)
<------>at java.base@17.0.7/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
```

...

```
Error during rewrite run
org.openrewrite.groovy.GroovyParsingException: Failed to parse test-gss/src/main/groovy/Kerberos.groovy at cursor position 5423. The next 10 characters in the original source are `void mkdir`
<------>at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:168)
<------>at org.openrewrite.groovy.GroovyParser.lambda$parseInputs$4(GroovyParser.java:154)
<------>at java.base@17.0.7/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
<------>at java.base@17.0.7/java.util.Collections$2.tryAdvance(Collections.java:4853)
```

...

```
There were problems parsing test-gss/src/main/groovy/TestPostgres.groovy
All sources parsed, running active recipes: org.openrewrite.java.OrderImports, org.openrewrite.staticanalysis.MissingOverrideAnnotation, io.github.pgjdbc.staticanalysis.CodeCleanup
Changes have been made to test-gss/src/main/groovy/PgJDBC.groovy by:
    io.github.pgjdbc.staticanalysis.CodeCleanup
        org.openrewrite.java.format.MethodParamPad
Changes have been made to test-gss/src/main/groovy/Util.groovy by:
    io.github.pgjdbc.staticanalysis.CodeCleanup
        org.openrewrite.java.format.MethodParamPad
Please review and commit the results.
Closing Git repo: pgjdbc/.git
```

**Comment by vlsi** [comment]
I guess it might be enough to replace https://github.com/openrewrite/rewrite-polyglot/blob/21833f2a67a8d37e836b516d58d351ad5cf9f002/src/main/java/org/openrewrite/polyglot/OmniParser.java#L126C15-L126C15 with `new FileTreeIterator(searchDir)`
